spring:
  profiles:
    active: dev
  application:
    name: apboa-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

server:
  port: 3065
