spring:
  profiles:
    active: dev
  application:
    name: Apboa-Gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: WARN
    com.hxh.apboa: INFO
